#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

#=============================================================================
# Title       : yabai
# Description : My Custom yabai Settings
# Author      : H.Y.
# LastUpdate  : 2021/05/24
# Since       : 2021/05/24
# Copyright   : © 2021 Digi-Angler
# License     : MIT License
# Version     : 1.0
#=============================================================================

#=============================================================================
# Personal Settings
#=============================================================================

# Layout Settings
# yabai -m config window_topmost               on
# yabai -m config window_shadow                off
# yabai -m config window_opacity               on
# yabai -m config window_opacity_duration      0.0
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.95
# yabai -m config window_border                on
# yabai -m config window_border_width          6
# yabai -m config active_window_border_color   0xff775759
# yabai -m config normal_window_border_color   0xff555555
# yabai -m config insert_feedback_color        0xaad75f5f
# yabai -m config split_ratio                  0.50
# yabai -m config auto_balance                 on

# Layout Space Settings
yabai -m config window_gap                   06
yabai -m config window_placement             second_child
yabai -m config layout                       bsp
yabai -m config top_padding                  6
yabai -m config bottom_padding               6
yabai -m config left_padding                 6
yabai -m config right_padding                6

# Mouse Settings
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# Debug
yabai -m config debug_output on

# Rules
yabai -m rule --add app="^Dictionary$"         sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$"       sticky=on layer=above manage=off
yabai -m rule --add app="^Postlab$"            sticky=on layer=above manage=off
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$"             sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^App Store$"          sticky=on layer=above manage=off

# restore position of floating windows when they are manually unfloated
# ~/Scripts/yabai_restore.sh

echo "yabai configuration loaded.."

# add the following to the end of your yabairc to have it launch automatically when yabai starts.
# make sure the limelight binary is added somewhere in your $PATH

# kill any existing limelight process if one exists, before we launch a new one
killall limelight &> /dev/null
limelight -c ~/.config/limelight/limelightrc &> /dev/null &
